// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY8E6CXU1w2eMJWenfy97ANsMIaLVlzkY',
    appId: '1:954153094298:web:78eb7f28d9d68b6bc56323',
    messagingSenderId: '954153094298',
    projectId: 'mynoteskx9595',
    authDomain: 'mynoteskx9595.firebaseapp.com',
    storageBucket: 'mynoteskx9595.appspot.com',
    measurementId: 'G-BE418BX1CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3drX4Uxin0y9QPmgXJCg9qaBYMksNLqI',
    appId: '1:954153094298:android:9dff0e5a1bc207edc56323',
    messagingSenderId: '954153094298',
    projectId: 'mynoteskx9595',
    storageBucket: 'mynoteskx9595.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT587BBIwEmk48RQzPzt5OXw8BWq0g9Ec',
    appId: '1:954153094298:ios:8ab0131f150f6ee5c56323',
    messagingSenderId: '954153094298',
    projectId: 'mynoteskx9595',
    storageBucket: 'mynoteskx9595.appspot.com',
    iosClientId: '954153094298-mpq6nah93gl9ed3tdkkj10mfm66dgh3e.apps.googleusercontent.com',
    iosBundleId: 'com.testprogram.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT587BBIwEmk48RQzPzt5OXw8BWq0g9Ec',
    appId: '1:954153094298:ios:8684ed85d42f2d9fc56323',
    messagingSenderId: '954153094298',
    projectId: 'mynoteskx9595',
    storageBucket: 'mynoteskx9595.appspot.com',
    iosClientId: '954153094298-2qfa4vgrpdgrcqrkr03j51b0nm3fl30j.apps.googleusercontent.com',
    iosBundleId: 'com.testprogram.mynotes.RunnerTests',
  );
}
